{
  "formatVersion": "1.1",
  "component": {
    "group": "net.minecraftforge",
    "module": "lowcodelanguage",
    "version": "1.20.1-47.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lowcodelanguage-1.20.1-47.3.0.jar",
          "url": "lowcodelanguage-1.20.1-47.3.0.jar",
          "size": 7398,
          "sha512": "3ac7cf73d08eb2515401bc83894258a74aee28474c14e3b093b5e56b6e8c903bf81ab8af5ef6e2834e6f2e2b99f4c235e8e551bf332cf38f36cbb42634ecdc25",
          "sha256": "adc594eac8c7b4983f008f39bd5460b51ef96849714db79d09e94d2be24319b9",
          "sha1": "1bf3e845ea0ce750096da8c71c8364b188ab74d4",
          "md5": "d295c4a25914cc6486c2e501ef432b18"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "fmlloader",
          "version": {
            "requires": "1.20.1-47.3.0"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "fmlcore",
          "version": {
            "requires": "1.20.1-47.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "lowcodelanguage-1.20.1-47.3.0.jar",
          "url": "lowcodelanguage-1.20.1-47.3.0.jar",
          "size": 7398,
          "sha512": "3ac7cf73d08eb2515401bc83894258a74aee28474c14e3b093b5e56b6e8c903bf81ab8af5ef6e2834e6f2e2b99f4c235e8e551bf332cf38f36cbb42634ecdc25",
          "sha256": "adc594eac8c7b4983f008f39bd5460b51ef96849714db79d09e94d2be24319b9",
          "sha1": "1bf3e845ea0ce750096da8c71c8364b188ab74d4",
          "md5": "d295c4a25914cc6486c2e501ef432b18"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lowcodelanguage-1.20.1-47.3.0-sources.jar",
          "url": "lowcodelanguage-1.20.1-47.3.0-sources.jar",
          "size": 3529,
          "sha512": "c74410dca622310da0c87c95e775671e3603c7ef13f206f1db41de63fe5a87bd8be008cc35072bdafb7d097823088cfbbdb85b6c02b53435221b01d16047116d",
          "sha256": "d633a5977625b472c259bc496be2e2ea68b3b3014b7beba0f364f277200a78ff",
          "sha1": "8a13e9c1521d327071ff450e2460d4bbc662e38b",
          "md5": "1d391ca61dd608c946350081ce7924ec"
        }
      ]
    }
  ]
}
