{
  "formatVersion": "1.1",
  "component": {
    "group": "net.minecraftforge",
    "module": "coremods",
    "version": "5.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.7"
          }
        }
      ],
      "files": [
        {
          "name": "coremods-5.1.6.jar",
          "url": "coremods-5.1.6.jar",
          "size": 24124,
          "sha512": "c8ca71245996f83ecd2b87756a717179e3fa70b6436a44f349c96cf2b7bbe8d3ea5b0b5b4effe43b439a6eae5b3a4f83a11bd37410e22c0f68b2d2fe9e090385",
          "sha256": "c6359febe1146dea046d957c2de1559686a4a110efe115e04593e5d4b9ee70cb",
          "sha1": "062fab3c3d59d37f8e15af311cb638c6f6123423",
          "md5": "4b4fe7e512819804660d621bf11c7381"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.openjdk.nashorn",
          "module": "nashorn-core",
          "version": {
            "requires": "15.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.7"
          }
        }
      ],
      "files": [
        {
          "name": "coremods-5.1.6.jar",
          "url": "coremods-5.1.6.jar",
          "size": 24124,
          "sha512": "c8ca71245996f83ecd2b87756a717179e3fa70b6436a44f349c96cf2b7bbe8d3ea5b0b5b4effe43b439a6eae5b3a4f83a11bd37410e22c0f68b2d2fe9e090385",
          "sha256": "c6359febe1146dea046d957c2de1559686a4a110efe115e04593e5d4b9ee70cb",
          "sha1": "062fab3c3d59d37f8e15af311cb638c6f6123423",
          "md5": "4b4fe7e512819804660d621bf11c7381"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "coremods-5.1.6-sources.jar",
          "url": "coremods-5.1.6-sources.jar",
          "size": 12363,
          "sha512": "6e7c96adc5d9e05f89521f85e824fbf12e3ff4249b7521d6d0d4c90906650807e73dfb5287d2c4f39d2f5ce61d739cf1460814027215c66245fda1d1425fd326",
          "sha256": "7a1ddee4e242efef076375cd7a011703f809b853b20befd657d193c7789855bd",
          "sha1": "5df143de774caf5aee3f5f64d2adf4014e7d4f40",
          "md5": "a106511ca6c7069b86637561d4e8d7f0"
        }
      ]
    }
  ]
}
