{
  "formatVersion": "1.1",
  "component": {
    "group": "net.minecraftforge",
    "module": "fmlcore",
    "version": "1.20.1-47.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "eventbus",
          "version": {
            "requires": "6.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "fmlcore-1.20.1-47.3.0.jar",
          "url": "fmlcore-1.20.1-47.3.0.jar",
          "size": 118685,
          "sha512": "1223df5f85ce4c719043824a2e6764a8daffba579c8285f98c61c3d9fccae288851ca1307a9a257a18f3f10f46c08fc9417c268dd5a900148227a6c6d8aee31b",
          "sha256": "6776a2a606d1d0633f9d14b66b2a9b7b8bb417e3c4d338925d15f997f6dbceb9",
          "sha1": "3b6be96aba3e323f3c918e8ef6a96312d82d76ad",
          "md5": "2ef1c9adb09cc3592e5e7185c90570c9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "fmlloader",
          "version": {
            "requires": "1.20.1-47.3.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "eventbus",
          "version": {
            "requires": "6.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "fmlcore-1.20.1-47.3.0.jar",
          "url": "fmlcore-1.20.1-47.3.0.jar",
          "size": 118685,
          "sha512": "1223df5f85ce4c719043824a2e6764a8daffba579c8285f98c61c3d9fccae288851ca1307a9a257a18f3f10f46c08fc9417c268dd5a900148227a6c6d8aee31b",
          "sha256": "6776a2a606d1d0633f9d14b66b2a9b7b8bb417e3c4d338925d15f997f6dbceb9",
          "sha1": "3b6be96aba3e323f3c918e8ef6a96312d82d76ad",
          "md5": "2ef1c9adb09cc3592e5e7185c90570c9"
        }
      ]
    }
  ]
}
