{
  "formatVersion": "1.1",
  "component": {
    "group": "net.minecraftforge",
    "module": "mclanguage",
    "version": "1.20.1-47.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mclanguage-1.20.1-47.3.0.jar",
          "url": "mclanguage-1.20.1-47.3.0.jar",
          "size": 4998,
          "sha512": "41130e3ffa305337aade5a951e67e9d15843e8f738fd12d9fde43c13f93b8467b8d3f9171beb7593204dda241f601a58bca2f1dc3008fb3f1a64d261dbd194a7",
          "sha256": "630e38190066a7f6b42e94809cb9395ddb807bf222103f8fb6af61f7259afd20",
          "sha1": "6093682e943ddccbabf70539319d7f2fe64db2e7",
          "md5": "09464464e54df9838666d62cf151c2c0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "fmlloader",
          "version": {
            "requires": "1.20.1-47.3.0"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "fmlcore",
          "version": {
            "requires": "1.20.1-47.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "mclanguage-1.20.1-47.3.0.jar",
          "url": "mclanguage-1.20.1-47.3.0.jar",
          "size": 4998,
          "sha512": "41130e3ffa305337aade5a951e67e9d15843e8f738fd12d9fde43c13f93b8467b8d3f9171beb7593204dda241f601a58bca2f1dc3008fb3f1a64d261dbd194a7",
          "sha256": "630e38190066a7f6b42e94809cb9395ddb807bf222103f8fb6af61f7259afd20",
          "sha1": "6093682e943ddccbabf70539319d7f2fe64db2e7",
          "md5": "09464464e54df9838666d62cf151c2c0"
        }
      ]
    }
  ]
}
